import { yourFunction } from './index.ts';

/**
 * @group 8kyu
 */
describe('8kyu - generated by npm run add:kata', () => {
    it('should', () => {
        expect(yourFunction()).toBe(true);
    });
});
